# Generated by Django 4.2.23 on 2025-10-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='pais',
            field=models.CharField(max_length=100),
        ),
    ]
